version: 2
updates:
  # Monitor ONLY NuGet dependencies for ChilledWindows (Actions updates are blocked)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

# Last manual check: 10/05/2026 01:00:29
